import { PopIcon, Reward, NotificationItem, Transaction, User } from '../types';

export const POP_ICONS: PopIcon[] = [
  {
    id: 'labubu',
    name: 'Labubu',
    character: 'The Monsters',
    color: '#E50012',
    bgColor: '#FFEAEB',
    accentColor: '#B3000E',
    emoji: '👹',
    description: 'Energetic monster with iconic mischievous smile & cute ears',
  },
  {
    id: 'molly',
    name: 'Molly',
    character: 'Space Molly',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    accentColor: '#1D4ED8',
    emoji: '👑',
    description: 'Iconic little girl with blue crown & curious pout',
  },
  {
    id: 'skullpanda',
    name: 'Skullpanda',
    character: 'City of Night',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    accentColor: '#6D28D9',
    emoji: '💀',
    description: 'Edgy, futuristic aesthetic with daring cyber elegance',
  },
  {
    id: 'dimoo',
    name: 'Dimoo',
    character: 'Retro Boy',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
    accentColor: '#0E7490',
    emoji: '☁️',
    description: 'Dreamy boy with soft fluffy cloud hair',
  },
  {
    id: 'crybaby',
    name: 'Crybaby',
    character: 'Sad Club',
    color: '#EAB308',
    bgColor: '#FEFCE8',
    accentColor: '#CA8A04',
    emoji: '🥺',
    description: 'Emotive bunny girl celebrating authentic feelings',
  },
  {
    id: 'hirono',
    name: 'Hirono',
    character: 'Little Mischief',
    color: '#F97316',
    bgColor: '#FFF7ED',
    accentColor: '#C2410C',
    emoji: '🦊',
    description: 'Deep and contemplative boy exploring inner worlds',
  },
  {
    id: 'pucky',
    name: 'Pucky',
    character: 'Fairies',
    color: '#EC4899',
    bgColor: '#FDF2F8',
    accentColor: '#BE185D',
    emoji: '🧚',
    description: 'Whimsical forest fairy with mushroom crown',
  },
  {
    id: 'sweetbean',
    name: 'Sweet Bean',
    character: 'Baby Series',
    color: '#10B981',
    bgColor: '#ECFDF5',
    accentColor: '#047857',
    emoji: '🍼',
    description: 'Chubby baby wearing cute pastel bear onesie',
  },
];

export const INITIAL_USER: User = {
  id: 'usr_8829120',
  name: 'Jayden Tan Jing Yuan',
  firstName: 'Jayden',
  lastName: 'Tan Jing Yuan',
  email: 'jaydentjy@gmail.com',
  emailVerified: true,
  phone: '+65 9888 8888',
  phoneVerified: true,
  dob: '01 April 2001',
  avatarId: 'labubu',
  membershipTier: 'Gold',
  points: 2450,
  pointsToNextTier: 550,
  nextTier: 'Platinum',
  tierProgress: 0.81,
  memberSince: 'October 2023',
  memberCode: 'PM-8829-9120',
  inAppNotifications: true,
  newsletter: true,
};

export const REWARDS: Reward[] = [
  {
    id: 'rew_1',
    title: '$10 In-Store Voucher',
    category: 'vouchers',
    pointsCost: 500,
    originalValue: '$10.00 SGD',
    description: 'Valid at any Pop Mart physical boutique store in Singapore. Cannot be combined with other discounts.',
    series: 'Voucher',
    stock: 280,
    badge: 'Popular',
    isPopular: true,
  },
  {
    id: 'rew_2',
    title: 'Skullpanda City of Night Blind Box',
    category: 'blind_box',
    pointsCost: 1500,
    originalValue: '$16.90 SGD',
    description: 'Redeem 1 sealed blind box from the bestselling Skullpanda City of Night collection. Collect all 12 variants!',
    series: 'Skullpanda',
    stock: 45,
    badge: 'Hot Drop',
    isPopular: true,
  },
  {
    id: 'rew_3',
    title: '$25 VIP Shopping Credit',
    category: 'vouchers',
    pointsCost: 1200,
    originalValue: '$25.00 SGD',
    description: 'Enjoy $25 off any order above $50. Eligible on both in-store and online app purchases.',
    series: 'Voucher',
    stock: 120,
    badge: 'Member Exclusive',
  },
  {
    id: 'rew_4',
    title: 'Labubu Monsters Fall In Wild Blind Box',
    category: 'blind_box',
    pointsCost: 1800,
    originalValue: '$18.90 SGD',
    description: 'Grab a guaranteed authentic sealed Labubu Monsters mystery box. Secret chaser edition chance 1:72.',
    series: 'Labubu',
    stock: 18,
    badge: 'Limited Stock',
  },
  {
    id: 'rew_5',
    title: 'Molly 100% Space Edition Pin Badge',
    category: 'merch',
    pointsCost: 800,
    originalValue: '$12.00 SGD',
    description: 'High gloss enamel collectible pin with metallic accents. Individually numbered collector backing card.',
    series: 'Space Molly',
    stock: 92,
  },
  {
    id: 'rew_6',
    title: 'Dimoo Retro Boy Series Blind Box',
    category: 'blind_box',
    pointsCost: 1600,
    originalValue: '$16.90 SGD',
    description: 'Step into nostalgic dreamy worlds with Dimoo Retro Series figures.',
    series: 'Dimoo',
    stock: 35,
  },
  {
    id: 'rew_7',
    title: 'Pop Mart Clear Display Show Box',
    category: 'merch',
    pointsCost: 650,
    originalValue: '$9.90 SGD',
    description: 'Stackable dust-proof acrylic showcase with magnetic door to protect your favorite collectible figures.',
    series: 'Accessories',
    stock: 150,
  },
  {
    id: 'rew_8',
    title: 'Crybaby Sad Club VIP Blind Box',
    category: 'blind_box',
    pointsCost: 1700,
    originalValue: '$17.90 SGD',
    description: 'Experience genuine emotion with Crybaby Sad Club series figures.',
    series: 'Crybaby',
    stock: 22,
  },
  {
    id: 'rew_9',
    title: 'Pop Mart Anniversary Canvas Tote',
    category: 'merch',
    pointsCost: 950,
    originalValue: '$15.00 SGD',
    description: 'Durable heavyweight cotton canvas tote bag featuring all classic Pop Mart character line art.',
    series: 'Apparel',
    stock: 64,
  },
  {
    id: 'rew_10',
    title: 'VIP Pass to Pop Toy Show (PTS)',
    category: 'exclusive',
    pointsCost: 3500,
    originalValue: '$50.00 SGD',
    description: 'Priority early entry pass to PTS with exclusive VIP gift bag and guaranteed queue ticket.',
    series: 'VIP Event',
    stock: 10,
    badge: 'Ultra Rare',
  },
];

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: '✨ Welcome to Pop Mart Rewards!',
    message: '500 bonus points have been added to your account for joining our loyalty program.',
    type: 'points',
    date: 'Today',
    time: '10:30 AM',
    isRead: false,
  },
  {
    id: 'notif_2',
    title: '🎁 $10 Voucher Expiring Soon',
    message: 'Your $10 In-Store Voucher is valid until 15 October 2026. Don\'t forget to redeem it!',
    type: 'reward',
    date: 'Yesterday',
    time: '2:15 PM',
    isRead: false,
  },
  {
    id: 'notif_3',
    title: '🛒 Points Earned: +150 PTS',
    message: 'Thank you for your purchase at Pop Mart Bugis Junction. 150 points added.',
    type: 'points',
    date: '01 Oct',
    time: '4:45 PM',
    isRead: true,
  },
  {
    id: 'notif_4',
    title: '🎉 Congratulations on Gold Tier!',
    message: 'You have unlocked Gold VIP status! Enjoy double points on birthday month & exclusive drop access.',
    type: 'system',
    date: '28 Sep',
    time: '11:00 AM',
    isRead: true,
  },
  {
    id: 'notif_5',
    title: '🚀 New Release: Dimoo Retro Boy',
    message: 'The wait is over! Dimoo Retro Boy series is now available online and in stores.',
    type: 'reward',
    date: '25 Sep',
    time: '9:00 AM',
    isRead: true,
  },
];

export const TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_1',
    title: 'In-Store Purchase',
    subtitle: 'Pop Mart Bugis Junction - Invoice #8841',
    points: 150,
    type: 'earned',
    date: '01 Oct 2026',
    icon: 'bag-handle',
  },
  {
    id: 'tx_2',
    title: 'Daily Check-in Streak',
    subtitle: '7-Day Check-in Bonus',
    points: 10,
    type: 'bonus',
    date: '30 Sep 2026',
    icon: 'calendar',
  },
  {
    id: 'tx_3',
    title: 'Redeemed $10 Voucher',
    subtitle: 'Coupon code: PM10-8829-XP',
    points: -500,
    type: 'redeemed',
    date: '28 Sep 2026',
    icon: 'ticket',
  },
  {
    id: 'tx_4',
    title: 'Birthday Gift Points',
    subtitle: 'Gold Tier Birthday Special',
    points: 200,
    type: 'bonus',
    date: '01 Apr 2026',
    icon: 'gift',
  },
  {
    id: 'tx_5',
    title: 'Welcome Loyalty Bonus',
    subtitle: 'New Member Registration',
    points: 500,
    type: 'bonus',
    date: '15 Oct 2025',
    icon: 'sparkles',
  },
];
